spring.application.name=transaction-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_transaction
spring.datasource.username=postgres
spring.datasource.password=asd@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
