spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_users
spring.datasource.username=postgres
spring.datasource.password=asd@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true