spring.application.name=account-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_accounts
spring.datasource.username=postgres
spring.datasource.password=asd@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true